module.exports = {
    AGENT_ORIGIN: 'https://localhost:8888',
    HISTORY: 'history',
    AGENT: 'agent',
    USER: 'user',
    MESSAGE: 'message',
    CLOSECHAT: 'closechat',
    BOT: 'bot',
    DEPT: 'department',
    USER_INACTIVE: 'userInactive',
    USER_ACTIVE: 'userActive',
    INVALID: 'invalid',
    VALID: 'valid',
    VALID_TOKEN: 'validToken',
    INVALID_TOKEN: 'invalidToken',
    NOCHAT: 'noChats',
    REFRESH: 'refresh',
};
